-- CreateTable
CREATE TABLE `document_settings` (
    `id` VARCHAR(191) NOT NULL,
    `tenantId` VARCHAR(191) NOT NULL,
    `propertyId` VARCHAR(191) NOT NULL,
    `companyName` VARCHAR(191) NULL,
    `companyNameEn` VARCHAR(191) NULL,
    `taxId` VARCHAR(191) NULL,
    `branchName` VARCHAR(191) NULL,
    `branchNumber` VARCHAR(191) NULL,
    `address` TEXT NULL,
    `addressEn` TEXT NULL,
    `phone` VARCHAR(191) NULL,
    `fax` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `website` VARCHAR(191) NULL,
    `logoUrl` VARCHAR(191) NULL,
    `logoWidth` INTEGER NULL DEFAULT 40,
    `logoPosition` VARCHAR(191) NOT NULL DEFAULT 'left',
    `bankName` VARCHAR(191) NULL,
    `bankBranch` VARCHAR(191) NULL,
    `bankAccountName` VARCHAR(191) NULL,
    `bankAccountNumber` VARCHAR(191) NULL,
    `primaryColor` VARCHAR(191) NOT NULL DEFAULT '#7C3AED',
    `showLogo` BOOLEAN NOT NULL DEFAULT true,
    `showCompanyName` BOOLEAN NOT NULL DEFAULT true,
    `showTaxId` BOOLEAN NOT NULL DEFAULT true,
    `showAddress` BOOLEAN NOT NULL DEFAULT true,
    `showPhone` BOOLEAN NOT NULL DEFAULT true,
    `showBankInfo` BOOLEAN NOT NULL DEFAULT false,
    `showSignatureLine` BOOLEAN NOT NULL DEFAULT true,
    `poTermsAndConditions` TEXT NULL,
    `poFooterNote` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `document_settings_tenantId_idx`(`tenantId`),
    INDEX `document_settings_propertyId_idx`(`propertyId`),
    UNIQUE INDEX `document_settings_tenantId_propertyId_key`(`tenantId`, `propertyId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
