/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Map: Prisma schema model name → name of the tenant scoping column.
 *
 * The keys here are the EXACT model names from prisma/schema.prisma
 * (PascalCase for new models, snake_case for legacy billing tables).
 * The Prisma extension callback receives this same form in its `model` arg.
 *
 * Two scoping column names exist in this schema:
 *   • `tenantId`  — camelCase (most newer models)
 *   • `tenant_id` — snake_case (legacy billing/subscription tables)
 *
 * To regenerate after schema changes:
 *   bash scripts/regenerate-tenant-scoped-models.sh
 */

export type TenantScopeField = 'tenantId' | 'tenant_id';

export const TENANT_SCOPED_MODELS: Readonly<Record<string, TenantScopeField>> = Object.freeze({
  AnalyticsEvent: 'tenantId',
  ApprovalFlow: 'tenantId',
  AuditLog: 'tenantId',
  Booking: 'tenantId',
  BookingAddOn: 'tenantId',
  Channel: 'tenantId',
  CostBudget: 'tenantId',
  CostCenter: 'tenantId',
  CostEntry: 'tenantId',
  CostKpiSnapshot: 'tenantId',
  CostType: 'tenantId',
  DocumentSequence: 'tenantId',
  DocumentSettings: 'tenantId',
  DpaAcceptance: 'tenantId',
  EmailLog: 'tenantId',
  EmailPreference: 'tenantId',
  Employee: 'tenantId',
  EmployeeCodeConfig: 'tenantId',
  GoodsReceive: 'tenantId',
  Guest: 'tenantId',
  HousekeepingTask: 'tenantId',
  HrAllowanceType: 'tenantId',
  HrAttendance: 'tenantId',
  HrDeductionType: 'tenantId',
  HrDepartment: 'tenantId',
  HrEvaluationCycle: 'tenantId',
  HrKpiTemplate: 'tenantId',
  HrLeaveRequest: 'tenantId',
  HrLeaveType: 'tenantId',
  HrPayroll: 'tenantId',
  HrPerformance: 'tenantId',
  HrPosition: 'tenantId',
  HrShiftType: 'tenantId',
  InventoryItem: 'tenantId',
  InventoryLot: 'tenantId',
  InventoryRecipe: 'tenantId',
  ItemCategory: 'tenantId',
  KitchenOrder: 'tenantId',
  LineNotifyToken: 'tenantId',
  LoyaltyPoint: 'tenantId',
  MaintenanceTask: 'tenantId',
  MenuCategory: 'tenantId',
  MenuEngineeringSnapshot: 'tenantId',
  MenuItem: 'tenantId',
  Notification: 'tenantId',
  OnboardingStep: 'tenantId',
  Order: 'tenantId',
  OrderItem: 'tenantId',
  PeriodClose: 'tenantId',
  PriceComparison: 'tenantId',
  PromptPayTransaction: 'tenantId',
  Property: 'tenantId',
  PurchaseOrder: 'tenantId',
  PurchaseRequisition: 'tenantId',
  PushNotificationDevice: 'tenantId',
  QCRecord: 'tenantId',
  QCTemplate: 'tenantId',
  Referral: 'tenantId',
  RequestForQuotation: 'tenantId',
  RevenueEntry: 'tenantId',
  RetailSale: 'tenantId',
  Restaurant: 'tenantId',
  RestaurantTable: 'tenantId',
  Review: 'tenantId',
  Room: 'tenantId',
  RoomTypeAmenityTemplate: 'tenantId',
  Staff: 'tenantId',
  StaffCall: 'tenantId',
  StockCount: 'tenantId',
  StockMovement: 'tenantId',
  Supplier: 'tenantId',
  SupplierQuote: 'tenantId',
  SupplierQuoteToken: 'tenantId',
  TableReservation: 'tenantId',
  User: 'tenantId',
  UserTenant: 'tenantId',
  Warehouse: 'tenantId',
  WasteRecord: 'tenantId',
  addon_trial_requests: 'tenant_id',
  announcement_reads: 'tenant_id',
  api_keys: 'tenant_id',
  data_export_requests: 'tenant_id',
  dunning_attempts: 'tenant_id',
  invoices: 'tenant_id',
  payments: 'tenant_id',
  subscription_coupon_redemptions: 'tenant_id',
  subscriptions: 'tenant_id',
  tenant_brandings: 'tenant_id',
  tenant_credits: 'tenant_id',
  usage_counters: 'tenant_id',
  usage_overage_charges: 'tenant_id',
});

/**
 * Models intentionally exempt from auto-scoping:
 *   • Platform-admin tables (plans, features, tenants, etc.)
 *   • Nested rows that derive scope via parent FK
 * The extension simply skips any model not present in TENANT_SCOPED_MODELS.
 */
export const PLATFORM_AND_NESTED_MODELS: ReadonlySet<string> = new Set([
  'Admin',
  'ApprovalFlowStep',
  'ApprovalFlowStepApprover',
  'BankAccount',
  'ContactDemo',
  'ContactMessage',
  'Coupon',
  'DepartmentPnL',
  'FeatureFlag',
  'FoodCostAnalysis',
  'GoodsReceiveItem',
  'HrKpiScore',
  'HrKpiTemplateItem',
  'HrPayrollItem',
  'InventoryRecipeIngredient',
  'ItemSupplier',
  'MenuEngineeringItem',
  'MenuItemRecipe',
  'PaymentAccount',
  'PaymentSettings',
  'Promotion',
  'PurchaseOrderItem',
  'PurchaseRequisitionItem',
  'PushNotificationLog',
  'PushNotificationPreference',
  'QCChecklistItem',
  'QCResult',
  'RecipeIngredient',
  'RetailSaleItem',
  'RefreshToken',
  'RfqPurchaseRequisition',
  'RfqSupplierRecipient',
  'RoomCostAnalysis',
  'StockCountItem',
  'SupplierQuoteItem',
  'User2FASettings',
  'WarehouseStock',
  'add_ons',
  'announcements',
  'billing_history',
  'features',
  'impersonation_sessions',
  'incident_updates',
  'incidents',
  'invoice_adjustments',
  'invoice_items',
  'password_resets',
  'payment_reconciliation_runs',
  'payment_refunds',
  'payment_webhook_events',
  'plan_addons',
  'plan_features',
  'plans',
  'service_components',
  'subscription_coupons',
  'subscription_feature_logs',
  'subscription_features',
  'tenants',
  'uptime_checks',
  'usage_metric_definitions',
]);
